[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "protisplice"
version = "0.1.0"
description = "A ML model for determining splice sites in protists."
authors = [
    { name = "Michael Bambha", email = "bambha.m@northeastern.edu" }
]
readme = "README.md"
requires.python = ">=3.7"
dependencies = [
    "pysam",
    "biopython",
    "pytest",
    "pyyaml"
]

[tool.setuptools]
package-dir = {"" = "src"}
py-modules = ["extract_splice_seqs"]